version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Taipei'
    open-pull-requests-limit: 10
    versioning-strategy: increase

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      timezone: 'Asia/Taipei'
    open-pull-requests-limit: 10
