name: Dependabot Test Build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  contents: read
  id-token: write

jobs:
  test-build:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Build Production
        run: yarn build